const router = require("express").Router();
const sortMiddleWare = require("../middleWares/sortMiddleWare");
const paginationMiddleWare=require("../middleWares/paginationMiddleWare");
const classesController = require("../controllers/classesController");
router.get("/home", classesController.index);
router.get("/createClass", classesController.classCreate);
router.post("/actionCreate", classesController.classActionCreate);
router.get("/:id/editClass", classesController.classEdit);
router.patch("/:id/actionEdit", classesController.classActionEdit);
router.get("/:id/editImage", classesController.classEditImage);
router.post("/actionDeleteImg", classesController.actionDeleteImg);
router.get("/:id/addStudents",sortMiddleWare,paginationMiddleWare,classesController.addStudents);
router.post("/:id/actionAddStudents", classesController.actionAddStudents);
router.get("/:id/classDetail",sortMiddleWare,paginationMiddleWare,classesController.classDetails);
router.get("/:id/addLeaveStudent",sortMiddleWare,paginationMiddleWare,classesController.addleaveStudent);
router.post("/:id/actionAddleaveStudent", classesController.actionAddleaveStudent);
router.get("/classesManage",classesController.classesManage);
router.get("/classesStorage",classesController.classesStorage);
router.post("/actionStateChange", classesController.actionStateChange);
module.exports = router;
